FROM wordpress:cli-php7.4

USER root

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install SVN, necessary to run install-wp-tests.sh
RUN apk update && apk add --no-cache subversion

# Install Node.js and npm
RUN apk add --update nodejs npm

# Ensure npm is available for www-data user
RUN chown -R www-data:www-data /usr/lib/node_modules /usr/bin/npm /usr/bin/npx

USER www-data
